# Vectors and Matrices in Numpy - Lab

## Introduction

This lab will ask you to perform some simple matrix creation and manipulation exercises based on what we have covered so far in this section. The key takeaway here for you is to be able to understand how to using indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays A (4x2) and B (2x3) 
```
A = 1402, 191 
    1371, 821 
    949, 1437
    147, 1448
    
B = 1, 2, 3
    4, 5, 6
    ```

In [3]:
import numpy as np
A = np.array([[1402, 191], [1371, 821], [949, 1437], [147, 1448]])
B = np.array([[1, 2, 3], [4, 5, 6]])

## 2. Print the dimensions of A and B 

In [5]:
# Code Here
print('Shape of A: {}'.format(A.shape))
print('Shape of B: {}'.format(B.shape))

Shape of A: (4, 2)
Shape of B: (2, 3)


## 3. Print some of the elements from A at following locations
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [6]:
print(A[0, 0])
print(A[0, 1])
print(A[2, 1])
print(A[3, 0])

1402
191
1437
147


## 4. Write a routine to populate matrix with random data
* Create an 3x3 numpy array with all zeros (use `np.zeros()`)
* Access each location i,j of this matrix and fill in random values between the range 1 and 10. 

In [15]:
M = np.zeros((3, 3))
print('Before: {}'.format(M))

import random

for x in range(0, M.shape[0]):
    for y in range(0, M.shape[1]):
        M[x, y] = random.randrange(1, 10)

print('After: {}'.format(M))

Before: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After: [[6. 8. 7.]
 [6. 2. 3.]
 [4. 9. 8.]]


## 5. Turn above routine into a function.
* Create two 4x4 zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [18]:
def random_add():
    A = np.zeros((4, 4))
    B = np.zeros((4, 4))
    for x in range(0, A.shape[0]):
        for y in range(0, A.shape[1]):
            A[x, y] = random.randrange(1, 10)
            B[x, y] = random.randrange(1, 10)
    C = A + B
    print('Final Output\n\n{}'.format(C))
    
random_add()

Final Output

[[10. 10. 14. 10.]
 [15.  9. 10. 12.]
 [10. 11. 11.  9.]
 [ 4.  9.  6.  9.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 